// PlutoCore - src/bot/modules/commands/info.ts
// Written by Quinn Lane - https://brndnln.dev/

import { Command } from 'discord-akairo'
import { Message } from 'discord.js'
import { genEmbed } from '../utilities/EmbedGenerator'
import config from '../../../configuration/config'
import { readdirSync } from 'fs'
import { client, pjson } from '../../pluto'
import { datFormat } from '../../../oob_modules/misc/jst'

export default class InfoCommand extends Command {
  constructor () {
    super('info', {
      aliases: [
        'info'
      ],
      category: 'Meta',
      description: {
        content: 'Gets basic info about the bot',
        usage: 'info'
      }
    })
  }

  async exec (message: Message) {
  	let commandCount: string
    let inhibitorCount: string
    let listenerCount: string

  	try {
      commandCount = readdirSync(__dirname).length.toString()
    } catch (e) {
  		commandCount = '0'
    }
    try {
      inhibitorCount = readdirSync(`${__dirname}/../inhibitors`).length.toString()
    } catch (e) {
      inhibitorCount = '0'
    }
    try {
      listenerCount = readdirSync(`${__dirname}/../listeners`).length.toString()
    } catch (e) {
      listenerCount = '0'
    }

    const discordJsVersion = pjson.dependencies['discord.js'].split('^')[1]
    const discordAkairoVersion = pjson.dependencies['discord-akairo'].split('^')[1]

    return await message.channel.send(genEmbed({
      title: ':information_source: Bot Info',
      description: `${config.bot.personalization.botName} is made by <@${config.bot.authorid}>`,
      footer: {
      	text: `Generated by ${message.author.tag}`,
        image: message.author.displayAvatarURL({ dynamic: true })
      },
      author: {
      	name: config.bot.personalization.embed.name,
        link: config.bot.personalization.embed.link,
        image: config.bot.personalization.embed.image
      },
      timestamp: true,
      color: config.bot.personalization.embed.defaultColors.normal,
      image: config.bot.personalization.socialPreviewImage,
      fields: [
        {
          name: 'Bot Version',
          value: `${config.bot.personalization.botName} version ${config.version}\nPlutoCore version ${config.version}`,
          inline: true
        },
        {
          name: 'Bot Modules',
          value: `${commandCount} total command(s)\n${inhibitorCount} total inhibitor(s)\n${listenerCount} total listener(s)`,
          inline: true
        },
        {
          name: 'Discord.js Version',
          value: `v${discordJsVersion} - [Find here](https://npmjs.com/package/discord.js/v/${discordJsVersion})`,
          inline: true
        },
        {
          name: 'Discord Akairo Version',
          value: `v${discordAkairoVersion} - [Find here](https://npmjs.com/package/discord-akairo/v/${discordAkairoVersion})`,
          inline: true
        },
        {
          name: 'Uptime',
          value: datFormat(process.uptime()),
          inline: true
        },
        {
          name: 'Guild Count',
          value: `I am in ${client.guilds.cache.array().length} guild(s)`,
          inline: true
        }
      ]
    }))
  }
}
