// Pluto - src/bot/modules/commands/msgreact.ts
// Written by Quinn Lane - https://brndnln.dev/

import { Command } from 'discord-akairo'
import { Message } from 'discord.js'
import { genEmbed } from '../utilities/EmbedGenerator'
import config from '../../../configuration/config'
import commander from 'commander'

export default class MessageReactCommand extends Command {
  constructor () {
    super('msgreact', {
      aliases: [
      	'msgreact',
        'react'
      ],
      ownerOnly: true,
      category: 'Reactions',
      description: {
        content: 'Manage automatic message reactions',
        usage: 'msgreact <subcommand> [args]',
        examples: [
          'msgreact status',
          'msgreact setemote :crab:',
          'msgreact settarget <@753729496724799588>'
        ]
      },
      args: [
        {
          id: 'subcommand',
          type: 'string',
          default: 'help'
        },
        {
          id: 'value',
          type: 'string',
          default: null
        }
      ]
    })
  }

  async exec (message: Message, args) {
    switch (args.subcommand) {
      case 'help':
        return await message.channel.send('```\nhelp\nstatus\nsetemote\nsettarget```')

      case 'status':
        const eStatus = genEmbed({
          title: ':flags: Message React Status',
          description: `**Enabled**: ${config.bot.commands.msgreact.enabled.toString()}\n**Emote**: ${config.bot.commands.msgreact.emote}\n**Target**: <@${config.bot.commands.msgreact.target}>`,
          color: '#86A397',
          author: {
          	name: config.bot.personalization.embed.name,
            link: config.bot.personalization.embed.link,
            image: config.bot.personalization.embed.image
          },
          footer: {
          	text: `Generated by ${message.author.tag}`,
            image: message.author.displayAvatarURL({ dynamic: true })
          },
          timestamp: true
        })
        return await message.channel.send(eStatus)
    }
  }
}
