// Pluto - src/bot/modules/commands/msgreact.ts
// Written by Quinn Lane - https://brndnln.dev/

import { Command } from 'discord-akairo'
import { Message } from 'discord.js'
import { genEmbed } from '../utilities/EmbedGenerator'
import config from '../../../configuration/config'

const subcommands = [
  'help',
  'status',
  'toggle',
  'setemote',
  'settarget'
]

export default class MessageReactCommand extends Command {
  constructor () {
    super('msgreact', {
      aliases: [
      	'msgreact',
        'react'
      ],
      ownerOnly: true,
      category: 'Reactions',
      description: {
        content: 'Manage automatic message reactions',
        usage: 'msgreact <subcommand> [args]',
        examples: [
          'msgreact status',
          'msgreact setemote :crab:',
          'msgreact settarget <@753729496724799588>'
        ]
      },
      args: [
        {
          id: 'subcommand',
          type: 'string',
          default: 'help'
        },
        {
          id: 'value',
          type: 'string',
          default: null
        }
      ]
    })
  }

  async sendHelp (message: Message) {
    const eHelp = genEmbed({
      title: ':question: Message Reactions - Help',
      description: subcommands.map(subcommand => ` - ${config.bot.prefix}msgreact ${subcommand}`),
      color: '#0c0910',
      author: {
        name: config.bot.personalization.embed.name,
        link: config.bot.personalization.embed.link,
        image: config.bot.personalization.embed.image
      },
      footer: {
        text: `Generated by ${message.author.tag}`,
        image: message.author.displayAvatarURL({ dynamic: true })
      },
      timestamp: true
    })

    return await message.channel.send(eHelp)
  }

  async exec (message: Message, args) {
    switch (args.subcommand) {
      case 'help':
      	return await this.sendHelp(message)

      case 'status':
        const eStatus = genEmbed({
          title: ':flags: Message Reactions - Status',
          description: `**Enabled:** ${config.bot.commands.msgreact.enabled.toString()}\n**Emote:** ${config.bot.commands.msgreact.emote}\n**Target:** <@${config.bot.commands.msgreact.target}>`,
          color: '#453750',
          author: {
          	name: config.bot.personalization.embed.name,
            link: config.bot.personalization.embed.link,
            image: config.bot.personalization.embed.image
          },
          footer: {
          	text: `Generated by ${message.author.tag}`,
            image: message.author.displayAvatarURL({ dynamic: true })
          },
          timestamp: true
        })

        return await message.channel.send(eStatus)

      case 'toggle':
        config.bot.commands.msgreact.enabled = !config.bot.commands.msgreact.enabled
        return await message.channel.send(genEmbed({
          title: '🚦 Message Reactions - Toggled',
          description: config.bot.commands.msgreact.enabled ? 'Message reactions have been enabled' : 'Message reactions have been disabled',
          color: '#73648a',
          author: {
            name: config.bot.personalization.embed.name,
            link: config.bot.personalization.embed.link,
            image: config.bot.personalization.embed.image
          },
          footer: {
            text: `Generated by ${message.author.tag}`,
            image: message.author.displayAvatarURL({ dynamic: true })
          },
          timestamp: true
        }))

      default:
        return await this.sendHelp(message)
    }
  }
}
