// PlutoCore - src/bot/modules/commands/toggledem.ts
// Written by Quinn Lane - https://brndnln.dev/

import { Command } from 'discord-akairo'
import { Message } from 'discord.js'
import { genEmbed } from '../utilities/EmbedGenerator'
import config from '../../../configuration/config'

class ToggleDEMCommand extends Command {
  constructor () {
    super('toggledem', {
      aliases: ['toggledem'],
      ownerOnly: true,
      category: 'Meta',
      description: {
        content: 'Toggle detailed error messages',
        usage: 'toggledem'
      }
    })
  }

  async exec (message: Message) {
    if (config.bot.personalization.detailedErrorMessages) {
      config.bot.personalization.detailedErrorMessages = false
      await message.channel.send(genEmbed({
        title: ':white_check_mark: Success!',
        description: 'Detailed error messages have been disabled',
        color: config.bot.personalization.embed.defaultColors.success,
        author: {
          name: config.bot.personalization.embed.name,
          image: config.bot.personalization.embed.image,
          link: config.bot.personalization.embed.link
        },
        footer: {
          text: `Generated by ${message.author.tag}`,
          image: message.author.displayAvatarURL({ dynamic: true })
        },
        timestamp: true
      }))
    } else {
      config.bot.personalization.detailedErrorMessages = true
      await message.channel.send(genEmbed({
        title: ':white_check_mark: Success!',
        description: 'Detailed error messages have been enabled',
        color: config.bot.personalization.embed.defaultColors.success,
        author: {
          name: config.bot.personalization.embed.name,
          image: config.bot.personalization.embed.image,
          link: config.bot.personalization.embed.link
        },
        footer: {
          text: `Generated by ${message.author.tag}`,
          image: message.author.displayAvatarURL({ dynamic: true })
        },
        timestamp: true
      }))
    }
  }
}

export default ToggleDEMCommand
