// PlutoCore - src/bot/modules/commands/ping.ts
// Written by Quinn Lane - https://brndnln.dev/

import { Command } from 'discord-akairo'
import config from '../../../../configuration/config'
// import { genEmbed } from '../utilities/EmbedGenerator'
import { client } from '../../../pluto'
import { genEmbed } from '../../utilities/EmbedGenerator'

export default class PingCommand extends Command {
  constructor () {
    super('ping', {
      aliases: [
      	'ping',
        'heartbeat'
      ],
      category: 'Meta',
      description: {
        content: 'Get the ping of the discord bot',
        usage: 'ping',
        examples: [
          'ping',
          'heartbeat'
        ]
      }
    })
  }

  async exec (message): Promise<any> {
    const sent = await message.channel.send('Pong!')
    const timeDiff = (sent.editedAt || sent.createdAt) - (message.editedAt || message.createdAt)
    await sent.delete()
    return await message.channel.send(genEmbed({
      title: ':ping_pong: Pong!',
      description: 'Network statistics for the bot',
      color: config.bot.personalization.embed.defaultColors.normal,
      footer: {
        text: `Generated by ${message.author.tag}`,
        image: message.author.displayAvatarURL({ dynamic: true })
      },
      author: {
        name: config.bot.personalization.embed.name,
        link: config.bot.personalization.embed.link,
        image: config.bot.personalization.embed.image
      },
      timestamp: true,
      fields: [
        {
          name: 'RTT',
          value: `🔂 ${timeDiff} ms`,
          inline: true
        },
        {
          name: 'Heartbeat',
          value: `💗 ${Math.round(this.client.ws.ping)} ms`,
          inline: true
        }
      ]
    }))
  }
}
