// PlutoCore - src/bot/modules/commands/akairo/commandhandler.ts
// Written by Quinn Lane - https://brndnln.dev/

import { Command } from 'discord-akairo'
import { Message } from 'discord.js'
import { genEmbed } from '../../utilities/EmbedGenerator'
import config from '../../../../configuration/config'
import { client } from '../../../pluto'

const actions = [
  'help',
  'load',
  'loadall',
  'register',
  'deregister',
  'reload',
  'reloadall',
  'remove',
  'removeall'
]

const color = '#003D5B'

async function sendHelp (message: Message) {
  return await message.channel.send(genEmbed({
    title: ':question: Command Handler - Help',
    description: actions.map(actionFromArray => ` - ${client.commandHandler.prefix}commandhandler ${actionFromArray}`),
    color: color,
    author: {
      name: config.bot.personalization.embed.name,
      image: config.bot.personalization.embed.image,
      link: config.bot.personalization.embed.link
    },
    footer: {
      text: `Generated by ${message.author.tag}`,
      image: message.author.displayAvatarURL({ dynamic: true })
    },
    timestamp: true
  }))
}

export default class CommandHandlerCommand extends Command {
  constructor () {
    super('commandhandler', {
      aliases: [
        'commandhandler'
      ],
      ownerOnly: true,
      category: 'Akairo',
      description: {
        content: 'Direct access to the command handler in discord-akairo',
        usage: 'commandhandler <action> [command]',
        examples: [
          'commandhandler',
          'commandhandler help',
          'commandhandler load ping'
        ]
      },
      args: [
        {
          id: 'action',
          type: 'string',
          default: 'help'
        },
        {
          id: 'command',
          type: 'command'
        }
      ]
    })
  }

  async exec (message: Message, { action, command }: { action: string, command: Command }) {
    switch (action) {
      case 'help':
        return await sendHelp(message)

      case 'load':
        if (command === null) {
          const loadErrorNoCommand = genEmbed({
            title: ':x: Error!',
            description: 'No command ID was specified',
            color: config.bot.personalization.embed.defaultColors.error,
            author: {
              name: config.bot.personalization.embed.name,
              image: config.bot.personalization.embed.image,
              link: config.bot.personalization.embed.link
            },
            footer: {
              text: `Generated by ${message.author.tag}`,
              image: message.author.displayAvatarURL({ dynamic: true })
            },
            timestamp: true
          })

          if (config.bot.personalization.detailedErrorMessages) {
            loadErrorNoCommand.addFields([
              {
                title: 'Syntax'
              }
            ])
          }

          return await message.channel.send(loadErrorNoCommand)
        }
        break

      default:
        return await sendHelp(message)
    }
  }
}
